development:
  adapter: postgresql
  encoding: unicode
  database: mirror
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mirror
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mirror_test
  pool: 5
  username:
  password:
